export const GET_INGRIDIENTS = "GET_INGRIDIENTS";
export const FETCH_INGRIDIENTS_FAILED = "FETCH_INGRIDIENTS_FAILED";
export const CHANGE_INGRIDIENTS = "CHANGE_INGRIDIENTS";

export const GET_ORDERS_START = "GET_ORDERS_START";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";

export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
